### ISSUE TITLE
Invalid Ticket triggers Plone login form instead of redirecting to CAS login

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/ftw.casauth#3]
If a user visits a Plone URL containing a `ticket` in the query string, like 

`http://localhost:8080/Plone/folder?ticket=ST-123-xxx`, and for whatever reason that ticket is invalid, the user will be sent to the **Plone login form** instead of the CAS server login.

The ticket may be invalid because
- the user mistakenly bookmarked an URL containing a ticket
- the URL was sent by E-Mail to a different user
- the user used the browser history to revisit an URL containing an expired ticket
- ...

My first idea was to trigger a redirect to the `service_url` with the `ticket` query string parameter stripped from it. This would IMHO be the ideal solution, because we don't really want the user have that ticket in their URLs anyway. However, a first  attempt at inserting a redirect [here](https://github.com/4teamwork/ftw.casauth/blob/c7c77a60f9074574c16a527e1c1c5304934fc812/ftw/casauth/plugin.py#L112) didn't work - Plone (PAS?) does send a `302`, but the `Location` header from the response then reads `http://localhost:8080/Plone/acl_users/credentials_cookie_auth/require_login?came_from=http%3A//localhost%3A8080/Plone/folder%3Fticket%3DST-123-xxxxx`

(The `Set-Cookie` does contain an `__ac_siteid` cookie however)

xref: https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20275

**Comment by senny** [comment]
It would be best to trigger another redirect after the ticket has been validated to make sure the `ticket` parameter does not appear in the address bar. The flow would look something like this:
1. GET `/` [Plone, casauth] => redirect to `/cas/login?service=/`
2. GET `/cas/login` [CAS] => redirect to `params[service]&ticket=SECRET`
3. GET `/` [Plone, casauth] => redirect to `params[service]`
